# Tensorflow2.0 小练习

In [41]:
import tensorflow as tf
import numpy as np

## 实现softmax函数

In [42]:
def softmax(x):
    ##########
    '''实现softmax函数，只要求对最后一维归一化，
    不允许用tf自带的softmax函数'''
    ##########
    x = tf.convert_to_tensor(x)
    max_val = tf.reduce_max(x, axis=-1, keepdims=True)
    #print(max_val)
    x_sub = x - max_val
    # print(x_sub)
    exp_x = tf.exp(x_sub)
    # print(exp_x)
    sum_exp = tf.reduce_sum(exp_x, axis=-1, keepdims=True)
    return exp_x / sum_exp

test_data = np.random.normal(size=[10, 5])
(softmax(test_data).numpy() - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [43]:
def sigmoid(x):
    ##########
    '''实现sigmoid函数， 不允许用tf自带的sigmoid函数'''
    ##########
    x = tf.convert_to_tensor(-x)
    exp_x = tf.exp(x)
    te_x=tf.ones([x.shape[0], x.shape[1]], dtype=tf.float64)+exp_x
    return 1/te_x

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data).numpy() - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [47]:
def softmax_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    x_log=tf.math.log(x)
    label=tf.convert_to_tensor(label)
    return tf.reduce_mean(tf.reduce_sum(-tf.multiply(x_log,label),axis=-1))

test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data))- softmax_ce(prob, label))**2 < 0.0001).numpy()

True

## 实现 sigmoid 交叉熵loss函数

In [63]:
def sigmoid_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    x_log=tf.math.log(x)
    x_t_log=tf.math.log(tf.ones(x_log.shape, dtype=tf.float64)-x)
    label=tf.convert_to_tensor(label)
    re=-tf.multiply(x_log,label)-tf.multiply(x_t_log,tf.ones(x_log.shape, dtype=tf.float64)-label)
    return tf.reduce_mean(re)

test_data = np.random.normal(size=[10])
prob = tf.nn.sigmoid(test_data)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print (label)

((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(prob, label))**2 < 0.0001).numpy()


[1. 1. 1. 0. 0. 1. 1. 1. 0. 1.]


True